# -*- coding: utf-8 -*-
"""Task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pftmV90XlDeY4V9hzu1voRxApi7-cZ7k
"""

!pip install torch

!pip install sentence-transformers==2.2.2

import pandas as pd
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

# Load dataset (adjust the file path as necessary)
df = pd.read_csv('/content/dataset.csv')

# Print the DataFrame's columns to check for the correct name
print(df.columns)

# Initialize the pre-trained model from Hugging Face
model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')

# Generate embeddings for product descriptions
df['embeddings'] = df['Description'].apply(lambda x: model.encode(x))

# Function to recommend similar products based on description
def recommend_similar_products(product_name, df, top_n=5):
    # Find the embedding of the given product name
    # Replace 'name' with the actual column name from your DataFrame
    target_product = df[df['ProductName'] == product_name]

    if target_product.empty:
        return f"Product '{product_name}' not found."

    # Get the embedding of the target product
    target_embedding = target_product['embeddings'].values[0].reshape(1, -1)

    # Calculate cosine similarity between the target product and all others
    df['similarity'] = df['embeddings'].apply(lambda x: cosine_similarity(target_embedding, x.reshape(1, -1)).item())

    # Sort by similarity, exclude the target product itself
    # Replace 'name' with the actual column name from your DataFrame
    similar_products = df[df['ProductName'] != product_name].sort_values(by='similarity', ascending=False)

    # Return top N similar products with their similarity scores
    # Replace 'name' with the actual column name from your DataFrame
    return similar_products[['ProductName', 'similarity']].head(top_n)

# Example usage: Recommend similar products to "Product X"
similar_products = recommend_similar_products('Bag', df)
print(similar_products)